---
- hosts: local
  roles:
    - homebrew
    - utils
    - tmux
    - git
    - zsh
    - vim
    #- golang
    - docker
    #- python
    - role: pyenv
      pyenv_root: "~/.pyenv"
      pyenv_runcom: "~/.profile"
      pyenv_versions: [3.6.1, 3.6.2, 2.7.14]
      pyenv_default_versions: "3.6.1:2.7.14"
    - pipenv
    - postgresql
    #- haskell
    - node
    - dev
    - common
    #- ruby
