---
- hosts: local
  roles:
    - homebrew
    - utils
    - tmux
    - git
    - zsh
    - vim
    #- golang
    - docker
    #- python
    - role: pyenv
      pyenv_versions: [3.6.0, 2.7.13]
    - postgresql
    #- haskell
    - node
    - dev
    - common
    #- ruby
