---
- name: install CLI tools
  homebrew: name={{ item }} state=present
  with_items:
    - tree
    - readline
    - wget
    - ack
    - ctags
    - sloccount
    - autoenv
    - ripgrep
    - jq
    - hledger
    #- hub
    #- s3cmd
    #- siege
  when: ansible_os_family == 'Darwin'
  tags: utils