- name: Ensure locale
  lineinfile:
    path: ~/.profile
    line: "{{ item }}"
    create: yes
  with_items:
    - "export LC_ALL=de_DE.utf-8"
    - "export LANG=de_DE.utf-8"
  tags: pipenv

- lineinfile:
    path: ~/.profile
    regexp: '^PATH="$HOME/.local/bin"'
    line: 'PATH="$HOME/.local/bin:$PATH"'
  tags: pipenv

- name: install pipenv
  homebrew: name={{ item }} state=latest
  with_items:
    - pipenv
  when: ansible_os_family == 'Darwin'
  tags: pipenv

- name: pipenv config
  lineinfile:
    path: ~/.profile
    line: 'export PIPENV_VENV_IN_PROJECT=1'
    create: yes
  tags: pipenv
