---
- name: install development libraries (Mac)
  homebrew:
    name: ['libevent', 'libmemcached', 'libxml2', 'libffi', 'gdal', 'gmp']
  when: ansible_os_family == 'Darwin'
  tags: dev

  #- name: unlink keg only
  #command: brew unlink {{ item}}
  #with_items:
  #  - libxml2
  #when: ansible_os_family == 'Darwin'

- name: Add development desktop tools
  homebrew_cask:
    name: [sequel-pro, slack, iterm2, atom]
  when: ansible_os_family == 'Darwin'
  tags: dev

- name: Virtualization for dev
  homebrew_cask:
    name: [docker, docker-compose]
  when: ansible_os_family == 'Darwin'
  tags: dev
